### ISSUE TITLE
Build failure: similar/main/multi.cpp:5749:20: error: unused variable ‘iff_error’

### ISSUE THREAD

**Issue by chewi** [dxx-rebirth/dxx-rebirth#790]
### Environment

Git: e8dd751d8a5cae375000fe7d3881e9da77075ab0

#### Operating System Environment

* [ ] Microsoft Windows (32-bit)
* [ ] Microsoft Windows (64-bit)
* [ ] Mac OS X

* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Fedora 31
  * [ ] Fedora 32
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)

* [ ] Arch
* [X] Gentoo (updated this week)

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)
* [ ] PowerPC (32-bit, sometimes called ppc)
* [ ] PowerPC64 (64-bit, big-endian, sometimes called ppc64)
* [ ] PowerPC64Le (64-bit, little-endian, sometimes called ppc64le)

### Description

When the editor is enabled, the build fails with:

```
similar/main/multi.cpp: In function ‘void d2x::save_hoard_data()’:
similar/main/multi.cpp:5749:20: error: unused variable ‘iff_error’ [-Werror=unused-variable]
 5749 |         const auto iff_error = read_result.status;
      |                    ^~~~~~~~~
similar/main/multi.cpp:5764:20: error: unused variable ‘iff_error’ [-Werror=unused-variable]
 5764 |         const auto iff_error = read_result.status;
      |                    ^~~~~~~~~
similar/main/multi.cpp:5777:20: error: unused variable ‘iff_error’ [-Werror=unused-variable]
 5777 |         const auto iff_error = iff_read_bitmap(i ? "orbb.bbm" : "orb.bbm", icon, &palette);
      |                    ^~~~~~~~~
```

I would have provided a fix, but I don't know how to address this.

I would like to politely request the addition of an option to disable -Werror. It is a real pain for distributions, especially source-based distributions where differing user environments may raise warnings you don't see yourself. This shouldn't prevent users from actually installing the package.

#### Regression status

Another Gentoo user reported this to me, so I don't know for sure when it started failing. Other issues are preventing me from checking, but 62494126ab2a159100468ec38e6ba8975a90a776 is probably the first failing commit.

### Steps to Reproduce

[sconf.log](https://github.com/user-attachments/files/15979929/sconf.log)
[dxxsconf.h.txt](https://github.com/user-attachments/files/15979928/dxxsconf.h.txt)

```
scons -j1 sdl2=0 sdlmixer=1 verbosebuild=1 debug=0 ipv6=0 opengl=1 use_tracker=0 prefix=/usr screenshot=png m_builddir=build/main/ m_editor=0 e_builddir=build/editor/ e_editor=1 d2x_sharepath=/usr/share/games/d2x d2x=m+e,site, register_install_target=0 build
scons: Reading SConscript files ...
===== D2X-Rebirth v0.61.0 0.60.0-beta2-3046-ge8dd751d8a5c e8dd751d8a5cae375000fe7d3881e9da77075ab0 =====
===== D2X-Rebirth v0.61.0 0.60.0-beta2-3046-ge8dd751d8a5c e8dd751d8a5cae375000fe7d3881e9da77075ab0 =====
DXX-Archive.3: compiling on 'linux'/'x86_64' for 'linux' into build/main/
DXX-Archive.3: checking version of C++ compiler 'x86_64-pc-linux-gnu-g++' ... 'x86_64-pc-linux-gnu-g++ (Gentoo 14.1.1_p20240622 p2) 14.1.1 20240622'
DXX-Archive.3: checking path to assembler ... b'/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/as'
DXX-Archive.3: checking version of assembler b'/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/as' ... 'GNU assembler (Gentoo 2.42 p3) 2.42.0'
DXX-Archive.3: checking path to linker ... b'ld.mold'
DXX-Archive.3: checking version of linker b'ld.mold' ... 'mold 2.31.0 (compatible with GNU ld)'
DXX-Archive.3: CHOST: 'x86_64-pc-linux-gnu'
DXX-Archive.3: CXX: 'x86_64-pc-linux-gnu-g++'
DXX-Archive.3: CPPDEFINES: [('PHYSFS_DEPRECATED', ''), ('DXX_USE_SHAREPATH', 1)]
DXX-Archive.3: CPPPATH: ['common/include', 'common/main', '.', 'build/main/']
DXX-Archive.3: CPPFLAGS: ['-Wno-sign-compare']
DXX-Archive.3: CXXFLAGS: ['-g', '-O2', '-ftabstop=4', '-Wall', '-Wformat=2', '-Werror=extra', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=vla', '-march=znver2', '-O2', '-pipe', '-frecord-gcc-switches', '-pthread', '-funsigned-char', '-march=znver2', '-O2', '-pipe', '-frecord-gcc-switches']
DXX-Archive.3: LIBS: None
DXX-Archive.3: LINKFLAGS: ['-Wl,-O1', '-Wl,--as-needed', '-Wl,--defsym=__gentoo_check_ldflags__=0', '-fuse-ld=mold', '-Wl,-O1', '-Wl,--as-needed', '-Wl,--defsym=__gentoo_check_ldflags__=0', '-fuse-ld=mold']
DXX-Archive.3: $CCACHE_PREFIX: None
DXX-Archive.3: $DISTCC_HOSTS: None
DXX-Archive.3: checking whether C++ compiler and linker work...yes
DXX-Archive.3: checking whether C++ compiler accepts -std=gnu++20...yes
DXX-Archive.3: checking endian to use...little
DXX-Archive.3: checking whether to enable word alignment fixups...no
DXX-Archive.3: building with OpenGL
DXX-Archive.3: checking whether to enable release options...yes
DXX-Archive.3: checking whether to enable memory allocation tracking...no
DXX-Archive.3: checking whether to enable level editor...no
DXX-Archive.3: checking whether to enable IPv6 support...no
DXX-Archive.3: checking whether to enable stereoscopic rendering...yes
DXX-Archive.3: checking whether to enable multiplayer over UDP...yes
DXX-Archive.3: checking whether to enable UDP game tracker...no
DXX-Archive.3: checking how to handle ADL MIDI...disabled
DXX-Archive.3: checking how to format screenshots...png
DXX-Archive.3: checking libpng pkg-config libpng
DXX-Archive.3: using pkg-config at discovered path /usr/bin/x86_64-pc-linux-gnu-pkg-config
DXX-Archive.3: reading libpng version from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --modversion libpng`
DXX-Archive.3: libpng version: '1.6.43'
DXX-Archive.3: reading libpng settings from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --cflags --libs libpng`
DXX-Archive.3: libpng settings: {'CPPPATH': ['/usr/include/libpng16'], 'LIBS': ['png16']}
DXX-Archive.3: checking for usable library png...yes
DXX-Archive.3: checking physfs pkg-config physfs
DXX-Archive.3: reading physfs version from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --modversion physfs`
DXX-Archive.3: physfs version: '3.0.2'
DXX-Archive.3: reading physfs settings from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --cflags --libs physfs`
DXX-Archive.3: physfs settings: {'LIBS': ['physfs']}
DXX-Archive.3: checking for usable library physfs...yes
DXX-Archive.3: checking for usable library ['GL', 'GLU']...yes
DXX-Archive.3: checking SDL pkg-config sdl
DXX-Archive.3: reading sdl version from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --modversion sdl`
DXX-Archive.3: SDL version: '1.2.68'
DXX-Archive.3: reading SDL settings from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --cflags --libs sdl`
DXX-Archive.3: SDL settings: {'CPPDEFINES': [['_GNU_SOURCE', '1'], '_REENTRANT'], 'CPPPATH': ['/usr/include/SDL'], 'LIBS': ['SDL']}
DXX-Archive.3: checking whether to enable joystick support...yes
DXX-Archive.3: checking for usable library SDL with OpenGL...yes
DXX-Archive.3: checking whether to use SDL_image...yes
DXX-Archive.3: checking SDL_image pkg-config SDL_image
DXX-Archive.3: reading SDL_image version from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --modversion SDL_image`
DXX-Archive.3: SDL_image version: '1.2.13'
DXX-Archive.3: reading SDL_image settings from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --cflags --libs SDL_image`
DXX-Archive.3: SDL_image settings: {'CPPDEFINES': [['_GNU_SOURCE', '1'], '_REENTRANT'], 'CPPPATH': ['/usr/include/SDL', '/usr/include/libpng16', '/usr/include/webp'], 'LIBS': ['SDL_image', 'SDL']}
DXX-Archive.3: checking for usable library SDL_image...yes
DXX-Archive.3: checking whether to use SDL_mixer...yes
DXX-Archive.3: checking SDL_mixer pkg-config SDL_mixer
DXX-Archive.3: reading SDL_mixer version from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --modversion SDL_mixer`
DXX-Archive.3: SDL_mixer version: '1.2.13'
DXX-Archive.3: reading SDL_mixer settings from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --cflags --libs SDL_mixer`
DXX-Archive.3: SDL_mixer settings: {'CCFLAGS': ['-pthread', '-pthread'], 'CPPDEFINES': [['_GNU_SOURCE', '1'], '_REENTRANT', '_DEFAULT_SOURCE', ['_XOPEN_SOURCE', '600']], 'CPPPATH': ['/usr/include/SDL', '/usr/include/opus', '/usr/include/pipewire-0.3', '/usr/include/spa-0.2', '/usr/include/dbus-1.0', '/usr/lib64/dbus-1.0/include', '/usr/include/elogind', '/usr/include/glib-2.0', '/usr/lib64/glib-2.0/include', '/usr/include/SDL2'], 'LIBS': ['SDL_mixer', 'SDL', 'pulse', 'gmodule-2.0', 'glib-2.0'], 'LINKFLAGS': ['-pthread', '-pthread']}
DXX-Archive.3: checking for usable library SDL_mixer...yes
DXX-Archive.3: checking whether compiler optimizes function __attribute__((__error__))...yes
DXX-Archive.3: checking whether compiler implements __builtin_bswap{16,32,64} functions...yes
DXX-Archive.3: checking whether compiler optimizes __builtin_constant_p...yes
DXX-Archive.3: checking whether compiler accepts __builtin_expect...yes
DXX-Archive.3: checking whether compiler accepts __builtin_FILE, __builtin_LINE...yes
DXX-Archive.3: checking whether compiler optimizes __builtin_object_size...yes
DXX-Archive.3: checking whether compiler understands embedded compound statements...yes
DXX-Archive.3: checking for function __attribute__((always_inline))...yes
DXX-Archive.3: checking for function __attribute__((alloc_size))...yes
DXX-Archive.3: checking for function __attribute__((cold))...yes
DXX-Archive.3: checking for function __attribute__((format_arg))...yes
DXX-Archive.3: checking for function __attribute__((format(printf)))...yes
DXX-Archive.3: checking for function __attribute__((malloc))...yes
DXX-Archive.3: checking for function __attribute__((nonnull))...yes
DXX-Archive.3: checking for function __attribute__((used))...yes
DXX-Archive.3: checking for function __attribute__((unused))...yes
DXX-Archive.3: checking whether compiler optimizes function __attribute__((__warning__))...yes
DXX-Archive.3: checking for C++11 intrinsic static_assert when true...yes
DXX-Archive.3: checking for C++11 intrinsic static_assert when false...yes
DXX-Archive.3: checking whether compiler handles classes from "using namespace"...yes
DXX-Archive.3: checking for required C++11, C++14, C++17, C++20 standard features...yes
DXX-Archive.3: checking when to pre-compile own headers...never
DXX-Archive.3: checking when to pre-compile system headers...never
DXX-Archive.3: checking whether compiler handles 20-element tuples...yes
DXX-Archive.3: checking whether to use overwrite poisoning...(cached) no
DXX-Archive.3: checking whether to use Valgrind poisoning...(cached) no
DXX-Archive.3: checking whether to format std::size_t with "%zu"...yes
DXX-Archive.3: checking whether compiler argument -Wuseless-cast works with SDL...yes
DXX-Archive.3: checking whether to cast operator-(T*,T*) to int...yes
DXX-Archive.3: checking whether to cast std::size_t to unsigned int...yes
DXX-Archive.3: checking for strcasecmp...yes
DXX-Archive.3: checking for getaddrinfo...yes
DXX-Archive.3: checking for struct timespec...yes
DXX-Archive.3: checking whether compiler accepts -Wimplicit-fallthrough=5...yes
DXX-Archive.3: checking whether compiler allows lambda capture of local references...yes
DXX-Archive.3: checking whether compiler accepts string literal operator templates...yes
DXX-Archive.3: checking whether compiler accepts braced variables as function arguments and return values...yes
DXX-Archive.3: checking whether compiler accepts preferred options...yes
DXX-Archive.3: checking whether to build runtime tests...no
DXX-Archive.3: CHOST: 'x86_64-pc-linux-gnu'
DXX-Archive.3: CXX: 'x86_64-pc-linux-gnu-g++'
DXX-Archive.3: CPPDEFINES: [('PHYSFS_DEPRECATED', ''), ('DXX_USE_SHAREPATH', 1)]
DXX-Archive.3: CPPPATH: ['common/include', 'common/main', '.', 'build/main/', '/usr/include/libpng16', '/usr/include/SDL', '/usr/include/webp', '/usr/include/opus', '/usr/include/pipewire-0.3', '/usr/include/spa-0.2', '/usr/include/dbus-1.0', '/usr/lib64/dbus-1.0/include', '/usr/include/elogind', '/usr/include/glib-2.0', '/usr/lib64/glib-2.0/include', '/usr/include/SDL2']
DXX-Archive.3: CPPFLAGS: ['-Wno-sign-compare']
DXX-Archive.3: CXXFLAGS: ['-g', '-ftabstop=4', '-Wall', '-Wformat=2', '-Werror=extra', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=vla', '-pthread', '-funsigned-char', '-march=znver2', '-O2', '-pipe', '-frecord-gcc-switches', '-std=gnu++20', '-Werror=unused', '-Werror=useless-cast', '-Wimplicit-fallthrough=5', '-fstrict-flex-arrays', '-fvisibility=hidden', '-Wduplicated-branches', '-Wduplicated-cond', '-Wstrict-flex-arrays', '-Wsuggest-attribute=noreturn', '-Wsuggest-final-types', '-Wsuggest-override', '-Wlogical-op', '-Wold-style-cast', '-Wredundant-decls']
DXX-Archive.3: LIBS: ['png16', 'physfs', 'SDL_image', 'SDL_mixer', 'SDL', 'pulse', 'gmodule-2.0', 'glib-2.0']
DXX-Archive.3: LINKFLAGS: ['-Wl,-O1', '-Wl,--as-needed', '-Wl,--defsym=__gentoo_check_ldflags__=0', '-fuse-ld=mold', '-pthread']
DXX-Archive.3: $CCACHE_PREFIX: None
DXX-Archive.3: $DISTCC_HOSTS: None
D2X-Rebirth.1: compiling on 'linux'/'x86_64' for 'linux' into build/main/ with prefix list ('d2x_m', 'd2x_site', 'd2x', 'm', 'site', '')
D2X-Rebirth.1: default sharepath is '/usr/share/games/d2x/'
D2X-Rebirth.1: CHOST: 'x86_64-pc-linux-gnu'
D2X-Rebirth.1: CXX: 'x86_64-pc-linux-gnu-g++'
D2X-Rebirth.1: CPPDEFINES: deque([('PHYSFS_DEPRECATED', ''), ('DXX_USE_SHAREPATH', 1), ('NDEBUG',), ('RELEASE',), '_REENTRANT', ('DXX_BUILD_DESCENT_II',), ('__STDC_FORMAT_MACROS',)])
D2X-Rebirth.1: CPPPATH: ['common/include', 'common/main', '.', 'build/main/', '/usr/include/libpng16', '/usr/include/SDL', '/usr/include/webp', '/usr/include/opus', '/usr/include/pipewire-0.3', '/usr/include/spa-0.2', '/usr/include/dbus-1.0', '/usr/lib64/dbus-1.0/include', '/usr/include/elogind', '/usr/include/glib-2.0', '/usr/lib64/glib-2.0/include', '/usr/include/SDL2', 'd2x-rebirth/main']
D2X-Rebirth.1: CPPFLAGS: ['-Wno-sign-compare']
D2X-Rebirth.1: CXXFLAGS: ['-g', '-O2', '-ftabstop=4', '-Wall', '-Wformat=2', '-Werror=extra', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=vla', '-pthread', '-funsigned-char', '-march=znver2', '-O2', '-pipe', '-frecord-gcc-switches', '-std=gnu++20', '-Werror=unused', '-Werror=useless-cast', '-Wimplicit-fallthrough=5', '-fstrict-flex-arrays', '-fvisibility=hidden', '-Wduplicated-branches', '-Wduplicated-cond', '-Wstrict-flex-arrays', '-Wsuggest-attribute=noreturn', '-Wsuggest-final-types', '-Wsuggest-override', '-Wlogical-op', '-Wold-style-cast', '-Wredundant-decls']
D2X-Rebirth.1: LIBS: ['png16', 'physfs', 'SDL_image', 'SDL_mixer', 'SDL', 'pulse', 'gmodule-2.0', 'glib-2.0', 'm', 'GL', 'GLU']
D2X-Rebirth.1: LINKFLAGS: ['-Wl,-O1', '-Wl,--as-needed', '-Wl,--defsym=__gentoo_check_ldflags__=0', '-fuse-ld=mold', '-pthread']
D2X-Rebirth.1: $CCACHE_PREFIX: None
D2X-Rebirth.1: $DISTCC_HOSTS: None
DXX-Archive.4: compiling on 'linux'/'x86_64' for 'linux' into build/editor/
DXX-Archive.4: checking version of C++ compiler 'x86_64-pc-linux-gnu-g++' ... 'x86_64-pc-linux-gnu-g++ (Gentoo 14.1.1_p20240622 p2) 14.1.1 20240622'
DXX-Archive.4: checking path to assembler ... b'/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/as'
DXX-Archive.4: checking version of assembler b'/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/as' ... 'GNU assembler (Gentoo 2.42 p3) 2.42.0'
DXX-Archive.4: checking path to linker ... b'ld.mold'
DXX-Archive.4: checking version of linker b'ld.mold' ... 'mold 2.31.0 (compatible with GNU ld)'
DXX-Archive.4: CHOST: 'x86_64-pc-linux-gnu'
DXX-Archive.4: CXX: 'x86_64-pc-linux-gnu-g++'
DXX-Archive.4: CPPDEFINES: [('PHYSFS_DEPRECATED', ''), ('DXX_USE_SHAREPATH', 1)]
DXX-Archive.4: CPPPATH: ['common/include', 'common/main', '.', 'build/editor/', 'common/include/editor']
DXX-Archive.4: CPPFLAGS: ['-Wno-sign-compare']
DXX-Archive.4: CXXFLAGS: ['-g', '-O2', '-ftabstop=4', '-Wall', '-Wformat=2', '-Werror=extra', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=vla', '-march=znver2', '-O2', '-pipe', '-frecord-gcc-switches', '-pthread', '-funsigned-char', '-march=znver2', '-O2', '-pipe', '-frecord-gcc-switches']
DXX-Archive.4: LIBS: None
DXX-Archive.4: LINKFLAGS: ['-Wl,-O1', '-Wl,--as-needed', '-Wl,--defsym=__gentoo_check_ldflags__=0', '-fuse-ld=mold', '-Wl,-O1', '-Wl,--as-needed', '-Wl,--defsym=__gentoo_check_ldflags__=0', '-fuse-ld=mold']
DXX-Archive.4: $CCACHE_PREFIX: None
DXX-Archive.4: $DISTCC_HOSTS: None
DXX-Archive.4: checking whether C++ compiler and linker work...yes
DXX-Archive.4: checking whether C++ compiler accepts -std=gnu++20...yes
DXX-Archive.4: checking endian to use...little
DXX-Archive.4: checking whether to enable word alignment fixups...no
DXX-Archive.4: building with OpenGL
DXX-Archive.4: checking whether to enable release options...yes
DXX-Archive.4: checking whether to enable memory allocation tracking...no
DXX-Archive.4: checking whether to enable level editor...yes
DXX-Archive.4: checking whether to enable IPv6 support...no
DXX-Archive.4: checking whether to enable stereoscopic rendering...yes
DXX-Archive.4: checking whether to enable multiplayer over UDP...yes
DXX-Archive.4: checking whether to enable UDP game tracker...no
DXX-Archive.4: checking how to handle ADL MIDI...disabled
DXX-Archive.4: checking how to format screenshots...png
DXX-Archive.4: checking libpng pkg-config libpng
DXX-Archive.4: reusing libpng settings from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --cflags --libs libpng`: {'CPPPATH': ['/usr/include/libpng16'], 'LIBS': ['png16']}
DXX-Archive.4: checking for usable library png...yes
DXX-Archive.4: checking physfs pkg-config physfs
DXX-Archive.4: reusing physfs settings from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --cflags --libs physfs`: {'LIBS': ['physfs']}
DXX-Archive.4: checking for usable library physfs...yes
DXX-Archive.4: checking for usable library ['GL', 'GLU']...yes
DXX-Archive.4: checking SDL pkg-config sdl
DXX-Archive.4: reusing SDL settings from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --cflags --libs sdl`: {'CPPDEFINES': [['_GNU_SOURCE', '1'], '_REENTRANT'], 'CPPPATH': ['/usr/include/SDL'], 'LIBS': ['SDL']}
DXX-Archive.4: checking whether to enable joystick support...yes
DXX-Archive.4: checking for usable library SDL with OpenGL...yes
DXX-Archive.4: checking whether to use SDL_image...yes
DXX-Archive.4: checking SDL_image pkg-config SDL_image
DXX-Archive.4: reusing SDL_image settings from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --cflags --libs SDL_image`: {'CPPDEFINES': [['_GNU_SOURCE', '1'], '_REENTRANT'], 'CPPPATH': ['/usr/include/SDL', '/usr/include/libpng16', '/usr/include/webp'], 'LIBS': ['SDL_image', 'SDL']}
DXX-Archive.4: checking for usable library SDL_image...yes
DXX-Archive.4: checking whether to use SDL_mixer...yes
DXX-Archive.4: checking SDL_mixer pkg-config SDL_mixer
DXX-Archive.4: reusing SDL_mixer settings from `/usr/bin/x86_64-pc-linux-gnu-pkg-config --cflags --libs SDL_mixer`: {'CCFLAGS': ['-pthread', '-pthread'], 'CPPDEFINES': [['_GNU_SOURCE', '1'], '_REENTRANT', '_DEFAULT_SOURCE', ['_XOPEN_SOURCE', '600']], 'CPPPATH': ['/usr/include/SDL', '/usr/include/opus', '/usr/include/pipewire-0.3', '/usr/include/spa-0.2', '/usr/include/dbus-1.0', '/usr/lib64/dbus-1.0/include', '/usr/include/elogind', '/usr/include/glib-2.0', '/usr/lib64/glib-2.0/include', '/usr/include/SDL2'], 'LIBS': ['SDL_mixer', 'SDL', 'pulse', 'gmodule-2.0', 'glib-2.0'], 'LINKFLAGS': ['-pthread', '-pthread']}
DXX-Archive.4: checking for usable library SDL_mixer...yes
DXX-Archive.4: checking whether compiler optimizes function __attribute__((__error__))...yes
DXX-Archive.4: checking whether compiler implements __builtin_bswap{16,32,64} functions...yes
DXX-Archive.4: checking whether compiler optimizes __builtin_constant_p...yes
DXX-Archive.4: checking whether compiler accepts __builtin_expect...yes
DXX-Archive.4: checking whether compiler accepts __builtin_FILE, __builtin_LINE...yes
DXX-Archive.4: checking whether compiler optimizes __builtin_object_size...yes
DXX-Archive.4: checking whether compiler understands embedded compound statements...yes
DXX-Archive.4: checking for function __attribute__((always_inline))...yes
DXX-Archive.4: checking for function __attribute__((alloc_size))...yes
DXX-Archive.4: checking for function __attribute__((cold))...yes
DXX-Archive.4: checking for function __attribute__((format_arg))...yes
DXX-Archive.4: checking for function __attribute__((format(printf)))...yes
DXX-Archive.4: checking for function __attribute__((malloc))...yes
DXX-Archive.4: checking for function __attribute__((nonnull))...yes
DXX-Archive.4: checking for function __attribute__((used))...yes
DXX-Archive.4: checking for function __attribute__((unused))...yes
DXX-Archive.4: checking whether compiler optimizes function __attribute__((__warning__))...yes
DXX-Archive.4: checking for C++11 intrinsic static_assert when true...yes
DXX-Archive.4: checking for C++11 intrinsic static_assert when false...yes
DXX-Archive.4: checking whether compiler handles classes from "using namespace"...yes
DXX-Archive.4: checking for required C++11, C++14, C++17, C++20 standard features...yes
DXX-Archive.4: checking when to pre-compile own headers...never
DXX-Archive.4: checking when to pre-compile system headers...never
DXX-Archive.4: checking whether compiler handles 20-element tuples...yes
DXX-Archive.4: checking whether to use overwrite poisoning...(cached) no
DXX-Archive.4: checking whether to use Valgrind poisoning...(cached) no
DXX-Archive.4: checking whether to format std::size_t with "%zu"...yes
DXX-Archive.4: checking whether compiler argument -Wuseless-cast works with SDL...yes
DXX-Archive.4: checking whether to cast operator-(T*,T*) to int...yes
DXX-Archive.4: checking whether to cast std::size_t to unsigned int...yes
DXX-Archive.4: checking for strcasecmp...yes
DXX-Archive.4: checking for getaddrinfo...yes
DXX-Archive.4: checking for struct timespec...yes
DXX-Archive.4: checking whether compiler accepts -Wimplicit-fallthrough=5...yes
DXX-Archive.4: checking whether compiler allows lambda capture of local references...yes
DXX-Archive.4: checking whether compiler accepts string literal operator templates...yes
DXX-Archive.4: checking whether compiler accepts braced variables as function arguments and return values...yes
DXX-Archive.4: checking whether compiler accepts preferred options...yes
DXX-Archive.4: checking whether to build runtime tests...no
DXX-Archive.4: CHOST: 'x86_64-pc-linux-gnu'
DXX-Archive.4: CXX: 'x86_64-pc-linux-gnu-g++'
DXX-Archive.4: CPPDEFINES: [('PHYSFS_DEPRECATED', ''), ('DXX_USE_SHAREPATH', 1)]
DXX-Archive.4: CPPPATH: ['common/include', 'common/main', '.', 'build/editor/', 'common/include/editor', '/usr/include/libpng16', '/usr/include/SDL', '/usr/include/webp', '/usr/include/opus', '/usr/include/pipewire-0.3', '/usr/include/spa-0.2', '/usr/include/dbus-1.0', '/usr/lib64/dbus-1.0/include', '/usr/include/elogind', '/usr/include/glib-2.0', '/usr/lib64/glib-2.0/include', '/usr/include/SDL2']
DXX-Archive.4: CPPFLAGS: ['-Wno-sign-compare']
DXX-Archive.4: CXXFLAGS: ['-g', '-ftabstop=4', '-Wall', '-Wformat=2', '-Werror=extra', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=vla', '-pthread', '-funsigned-char', '-march=znver2', '-O2', '-pipe', '-frecord-gcc-switches', '-std=gnu++20', '-Werror=unused', '-Werror=useless-cast', '-Wimplicit-fallthrough=5', '-fstrict-flex-arrays', '-fvisibility=hidden', '-Wduplicated-branches', '-Wduplicated-cond', '-Wstrict-flex-arrays', '-Wsuggest-attribute=noreturn', '-Wsuggest-final-types', '-Wsuggest-override', '-Wlogical-op', '-Wold-style-cast', '-Wredundant-decls']
DXX-Archive.4: LIBS: ['png16', 'physfs', 'SDL_image', 'SDL_mixer', 'SDL', 'pulse', 'gmodule-2.0', 'glib-2.0']
DXX-Archive.4: LINKFLAGS: ['-Wl,-O1', '-Wl,--as-needed', '-Wl,--defsym=__gentoo_check_ldflags__=0', '-fuse-ld=mold', '-pthread']
DXX-Archive.4: $CCACHE_PREFIX: None
DXX-Archive.4: $DISTCC_HOSTS: None
D2X-Rebirth.2: compiling on 'linux'/'x86_64' for 'linux' into build/editor/ with prefix list ('d2x_e', 'd2x_site', 'd2x', 'e', 'site', '')
D2X-Rebirth.2: default sharepath is '/usr/share/games/d2x/'
D2X-Rebirth.2: CHOST: 'x86_64-pc-linux-gnu'
D2X-Rebirth.2: CXX: 'x86_64-pc-linux-gnu-g++'
D2X-Rebirth.2: CPPDEFINES: deque([('PHYSFS_DEPRECATED', ''), ('DXX_USE_SHAREPATH', 1), ('NDEBUG',), ('RELEASE',), '_REENTRANT', ('DXX_BUILD_DESCENT_II',), ('__STDC_FORMAT_MACROS',)])
D2X-Rebirth.2: CPPPATH: ['common/include', 'common/main', '.', 'build/editor/', 'common/include/editor', '/usr/include/libpng16', '/usr/include/SDL', '/usr/include/webp', '/usr/include/opus', '/usr/include/pipewire-0.3', '/usr/include/spa-0.2', '/usr/include/dbus-1.0', '/usr/lib64/dbus-1.0/include', '/usr/include/elogind', '/usr/include/glib-2.0', '/usr/lib64/glib-2.0/include', '/usr/include/SDL2', 'd2x-rebirth/main']
D2X-Rebirth.2: CPPFLAGS: ['-Wno-sign-compare']
D2X-Rebirth.2: CXXFLAGS: ['-g', '-O2', '-ftabstop=4', '-Wall', '-Wformat=2', '-Werror=extra', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=vla', '-pthread', '-funsigned-char', '-march=znver2', '-O2', '-pipe', '-frecord-gcc-switches', '-std=gnu++20', '-Werror=unused', '-Werror=useless-cast', '-Wimplicit-fallthrough=5', '-fstrict-flex-arrays', '-fvisibility=hidden', '-Wduplicated-branches', '-Wduplicated-cond', '-Wstrict-flex-arrays', '-Wsuggest-attribute=noreturn', '-Wsuggest-final-types', '-Wsuggest-override', '-Wlogical-op', '-Wold-style-cast', '-Wredundant-decls']
D2X-Rebirth.2: LIBS: ['png16', 'physfs', 'SDL_image', 'SDL_mixer', 'SDL', 'pulse', 'gmodule-2.0', 'glib-2.0', 'm', 'GL', 'GLU']
D2X-Rebirth.2: LINKFLAGS: ['-Wl,-O1', '-Wl,--as-needed', '-Wl,--defsym=__gentoo_check_ldflags__=0', '-fuse-ld=mold', '-pthread']
D2X-Rebirth.2: $CCACHE_PREFIX: None
D2X-Rebirth.2: $DISTCC_HOSTS: None
scons: done reading SConscript files.
scons: Building targets ...
scons: Configure: creating build/editor/dxxsconf.h

<SNIP DUE TO GITHUB LIMIT>

x86_64-pc-linux-gnu-g++ -c -g -O2 -ftabstop=4 -Wall -Wformat=2 -Werror=extra -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -pthread -funsigned-char -march=znver2 -O2 -pipe -frecord-gcc-switches -std=gnu++20 -Werror=unused -Werror=useless-cast -Wimplicit-fallthrough=5 -fstrict-flex-arrays -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wstrict-flex-arrays -Wsuggest-attribute=noreturn -Wsuggest-final-types -Wsuggest-override -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -DPHYSFS_DEPRECATED= -DDXX_USE_SHAREPATH=1 -DNDEBUG -DRELEASE -D_REENTRANT -DDXX_BUILD_DESCENT_II -D__STDC_FORMAT_MACROS -Icommon/include -Icommon/main -I. -Ibuild/editor -Icommon/include/editor -I/usr/include/libpng16 -I/usr/include/SDL -I/usr/include/webp -I/usr/include/opus -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/elogind -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/SDL2 -Id2x-rebirth/main similar/main/lighting.cpp -o build/editor/similar/main/.d2x-rebirth.lighting.o
In file included from common/main/render_state.h:5,
                 from similar/main/lighting.cpp:32:
build/editor/dxxsconf.h:32:9: warning: "_DEFAULT_SOURCE" redefined
   32 | #define _DEFAULT_SOURCE
      |         ^~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/x86_64-pc-linux-gnu/bits/os_defines.h:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/x86_64-pc-linux-gnu/bits/c++config.h:680,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_algobase.h:59,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/algorithm:60,
                 from similar/main/lighting.cpp:26:
/usr/include/features.h:238:10: note: this is the location of the previous definition
  238 | # define _DEFAULT_SOURCE    1
      |          ^~~~~~~~~~~~~~~
build/editor/dxxsconf.h:33:9: warning: "_XOPEN_SOURCE" redefined
   33 | #define _XOPEN_SOURCE 600
      |         ^~~~~~~~~~~~~
/usr/include/features.h:216:10: note: this is the location of the previous definition
  216 | # define _XOPEN_SOURCE  700
      |          ^~~~~~~~~~~~~
x86_64-pc-linux-gnu-g++ -c -g -O2 -ftabstop=4 -Wall -Wformat=2 -Werror=extra -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -pthread -funsigned-char -march=znver2 -O2 -pipe -frecord-gcc-switches -std=gnu++20 -Werror=unused -Werror=useless-cast -Wimplicit-fallthrough=5 -fstrict-flex-arrays -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wstrict-flex-arrays -Wsuggest-attribute=noreturn -Wsuggest-final-types -Wsuggest-override -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -DPHYSFS_DEPRECATED= -DDXX_USE_SHAREPATH=1 -DNDEBUG -DRELEASE -D_REENTRANT -DDXX_BUILD_DESCENT_II -D__STDC_FORMAT_MACROS -Icommon/include -Icommon/main -I. -Ibuild/editor -Icommon/include/editor -I/usr/include/libpng16 -I/usr/include/SDL -I/usr/include/webp -I/usr/include/opus -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/elogind -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/SDL2 -Id2x-rebirth/main similar/main/menu.cpp -o build/editor/similar/main/.d2x-rebirth.menu.o
x86_64-pc-linux-gnu-g++ -c -g -O2 -ftabstop=4 -Wall -Wformat=2 -Werror=extra -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -pthread -funsigned-char -march=znver2 -O2 -pipe -frecord-gcc-switches -std=gnu++20 -Werror=unused -Werror=useless-cast -Wimplicit-fallthrough=5 -fstrict-flex-arrays -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wstrict-flex-arrays -Wsuggest-attribute=noreturn -Wsuggest-final-types -Wsuggest-override -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -DPHYSFS_DEPRECATED= -DDXX_USE_SHAREPATH=1 -DNDEBUG -DRELEASE -D_REENTRANT -DDXX_BUILD_DESCENT_II -D__STDC_FORMAT_MACROS -Icommon/include -Icommon/main -I. -Ibuild/editor -Icommon/include/editor -I/usr/include/libpng16 -I/usr/include/SDL -I/usr/include/webp -I/usr/include/opus -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/elogind -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/SDL2 -Id2x-rebirth/main similar/main/mglobal.cpp -o build/editor/similar/main/.d2x-rebirth.mglobal.o
In file included from common/include/dsx-ns.h:9,
                 from common/include/maths.h:21,
                 from similar/main/mglobal.cpp:26:
build/editor/dxxsconf.h:32:9: warning: "_DEFAULT_SOURCE" redefined
   32 | #define _DEFAULT_SOURCE
      |         ^~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/x86_64-pc-linux-gnu/bits/os_defines.h:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/x86_64-pc-linux-gnu/bits/c++config.h:680,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/cstdint:38,
                 from common/include/maths.h:11:
/usr/include/features.h:238:10: note: this is the location of the previous definition
  238 | # define _DEFAULT_SOURCE    1
      |          ^~~~~~~~~~~~~~~
build/editor/dxxsconf.h:33:9: warning: "_XOPEN_SOURCE" redefined
   33 | #define _XOPEN_SOURCE 600
      |         ^~~~~~~~~~~~~
/usr/include/features.h:216:10: note: this is the location of the previous definition
  216 | # define _XOPEN_SOURCE  700
      |          ^~~~~~~~~~~~~
x86_64-pc-linux-gnu-g++ -c -g -O2 -ftabstop=4 -Wall -Wformat=2 -Werror=extra -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -pthread -funsigned-char -march=znver2 -O2 -pipe -frecord-gcc-switches -std=gnu++20 -Werror=unused -Werror=useless-cast -Wimplicit-fallthrough=5 -fstrict-flex-arrays -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wstrict-flex-arrays -Wsuggest-attribute=noreturn -Wsuggest-final-types -Wsuggest-override -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -DPHYSFS_DEPRECATED= -DDXX_USE_SHAREPATH=1 -DNDEBUG -DRELEASE -D_REENTRANT -DDXX_BUILD_DESCENT_II -D__STDC_FORMAT_MACROS -Icommon/include -Icommon/main -I. -Ibuild/editor -Icommon/include/editor -I/usr/include/libpng16 -I/usr/include/SDL -I/usr/include/webp -I/usr/include/opus -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/elogind -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/SDL2 -Id2x-rebirth/main similar/main/mission.cpp -o build/editor/similar/main/.d2x-rebirth.mission.o
x86_64-pc-linux-gnu-g++ -c -g -O2 -ftabstop=4 -Wall -Wformat=2 -Werror=extra -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -pthread -funsigned-char -march=znver2 -O2 -pipe -frecord-gcc-switches -std=gnu++20 -Werror=unused -Werror=useless-cast -Wimplicit-fallthrough=5 -fstrict-flex-arrays -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wstrict-flex-arrays -Wsuggest-attribute=noreturn -Wsuggest-final-types -Wsuggest-override -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -DPHYSFS_DEPRECATED= -DDXX_USE_SHAREPATH=1 -DNDEBUG -DRELEASE -D_REENTRANT -DDXX_BUILD_DESCENT_II -D__STDC_FORMAT_MACROS -Icommon/include -Icommon/main -I. -Ibuild/editor -Icommon/include/editor -I/usr/include/libpng16 -I/usr/include/SDL -I/usr/include/webp -I/usr/include/opus -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/elogind -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/SDL2 -Id2x-rebirth/main similar/main/morph.cpp -o build/editor/similar/main/.d2x-rebirth.morph.o
x86_64-pc-linux-gnu-g++ -c -g -O2 -ftabstop=4 -Wall -Wformat=2 -Werror=extra -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -pthread -funsigned-char -march=znver2 -O2 -pipe -frecord-gcc-switches -std=gnu++20 -Werror=unused -Werror=useless-cast -Wimplicit-fallthrough=5 -fstrict-flex-arrays -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wstrict-flex-arrays -Wsuggest-attribute=noreturn -Wsuggest-final-types -Wsuggest-override -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -DPHYSFS_DEPRECATED= -DDXX_USE_SHAREPATH=1 -DNDEBUG -DRELEASE -D_REENTRANT -DDXX_BUILD_DESCENT_II -D__STDC_FORMAT_MACROS -Icommon/include -Icommon/main -I. -Ibuild/editor -Icommon/include/editor -I/usr/include/libpng16 -I/usr/include/SDL -I/usr/include/webp -I/usr/include/opus -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/elogind -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/SDL2 -Id2x-rebirth/main similar/main/multi.cpp -o build/editor/similar/main/.d2x-rebirth.multi.o
similar/main/multi.cpp: In function ‘void d2x::save_hoard_data()’:
similar/main/multi.cpp:5749:20: error: unused variable ‘iff_error’ [-Werror=unused-variable]
 5749 |         const auto iff_error = read_result.status;
      |                    ^~~~~~~~~
similar/main/multi.cpp:5764:20: error: unused variable ‘iff_error’ [-Werror=unused-variable]
 5764 |         const auto iff_error = read_result.status;
      |                    ^~~~~~~~~
similar/main/multi.cpp:5777:20: error: unused variable ‘iff_error’ [-Werror=unused-variable]
 5777 |         const auto iff_error = iff_read_bitmap(i ? "orbb.bbm" : "orb.bbm", icon, &palette);
      |                    ^~~~~~~~~
cc1plus: some warnings being treated as errors
scons: *** [build/editor/similar/main/.d2x-rebirth.multi.o] Error 1
scons: building terminated because of errors.
Failed target count: total=1; targets with enable_build_failure_summary=1: 1
Failed node list:
        build/editor/similar/main/.d2x-rebirth.multi.o
Failed command list:
 x86_64-pc-linux-gnu-g++ -c -g -O2 -ftabstop=4 -Wall -Wformat=2 -Werror=extra -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -pthread -funsigned-char -march=znver2 -O2 -pipe -frecord-gcc-switches -std=gnu++20 -Werror=unused -Werror=useless-cast -Wimplicit-fallthrough=5 -fstrict-flex-arrays -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wstrict-flex-arrays -Wsuggest-attribute=noreturn -Wsuggest-final-types -Wsuggest-override -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -DPHYSFS_DEPRECATED= -DDXX_USE_SHAREPATH=1 -DNDEBUG -DRELEASE -D_REENTRANT -DDXX_BUILD_DESCENT_II -D__STDC_FORMAT_MACROS -Icommon/include -Icommon/main -I. -Ibuild/editor -Icommon/include/editor -I/usr/include/libpng16 -I/usr/include/SDL -I/usr/include/webp -I/usr/include/opus -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/elogind -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/SDL2 -Id2x-rebirth/main "similar/main/multi.cpp" -o "build/editor/similar/main/.d2x-rebirth.multi.o"
```

**Comment by vLKp** [comment]
> I would have provided a fix, but I don't know how to address this.

This variable is used in an `assert`, which gets compiled away by `-DNDEBUG`.  I build test the editor, but I always build the editor with assertions enabled, so the `assert` is present for me and the variable is used.

The faulting code is very old, and I think it was a mistake for the original author to use `assert` here.  It looks like one of my currently unpublished changes fixes this site.  I'll try to get that commit pushed soon.  If you would rather not wait, add a `(void)iff_error;` on the line after the definition.  That will make it "used" from the compiler's perspective, without changing the generated code.

---

> I would like to politely request the addition of an option to disable -Werror.

Noted.  I have considered this before, out of concern that a well-meaning but misguided distributor would simply disable all uses of `-Werror` in the script.  I think doing _that_ could confuse the configure tests, some of which may rely on warnings-as-errors when probing for potentially unsupported constructs.  Adding an option to let the configure tests use `-Werror` where they need it, but not pass it to any of the actual compile commands, should be straightforward, and achieve what you want.  I haven't written such a commit up yet, but will keep it in mind.

I will note that I always build with `-Werror` locally, and enable some other warning options that the distributed build does not.  However, logic errors like this one, where I did not build test a particular option combination, can still slip through.

> Other issues are preventing me from checking, but 6249412 is probably the first failing commit.

Agreed.  It dropped the outer scope `(void)` cast because the variable was moved to an inner scope.  Non-editor builds do not include this code.  Editor builds with debug-enabled include the code and an `assert` that consumes the variable, rendering it used.  Editor builds with debug-disabled trigger the warning.

**Comment by vLKp** [comment]
Commit 6df7efe97809ff9b27e9eeada587249019793ec0 should resolve the unused-variable warning reported here.

Commit c7218ed2d1aec64dfeb7f8908d16d1e4501ff719 removes the automatic `-Werror=` on selected warnings for the main source units.  On consideration, I decided that adding a knob was excessive, since distributions will normally want warnings-are-not-errors, I want warnings-as-errors for my builds, and I would hope that outside contributors are conscientious enough to build with warnings-as-errors.  However, anyone who wants it can already enable warnings-as-errors for select warnings or even for all warnings by adding an appropriate option to their `$CXXFLAGS` (and my personal build has been that way for years, using a full `-Werror` instead of only enabling errors for specific warnings).  If I default it enabled, distributions would need to adjust their build script to choose to have it disabled, in addition to updating to a version that supports it.  I get very little in the way of outside contributions, so I doubt warnings-as-errors has an effect on the quality of submissions I get.

**Comment by chewi** [comment]
Many thanks. I'm still seeing `-Werror=unused -Werror=useless-cast` throughout the build, but I'm guessing that was intended. I think we can close this now.
